#!/bin/bash -l

#SBATCH --job-name=hydro
#SBATCH --time=24:00:00
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#SBATCH --nodes=1
#SBATCH --account=s754
#SBATCH --cpus-per-task=12

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

echo running > job.status

. ./run

echo "Done."
echo done > job.status

