#!/usr/bin/env python

dir0 = set(dir()) | {"dir0"}

Red = 10.
alpha = 8.
gamma = 8.
We = 0.5
zeta = 0.125
zeta2 = 0.08

alpha = 0.1
gamma = 0.1

rhoo = 1.
Uc = 1.
H = 1.
x0 = 0.3 * H
x02 = 0.7 * H
y0 = (0.9 - zeta) * H
y02 = (0.9 - zeta2) * H
W = 0.375 * H
z0 = W * 0.5

T = 5. * H / Uc
dt = 1e-6 * H / Uc

a = zeta * H
a2 = zeta2 * H
d = 2 * a
rhoi = alpha * rhoo
muo = rhoo * Uc * d / Red
mui = gamma * muo
sigma = rhoo * Uc ** 2 * d / We
pgrad = 8 * Uc * muo / H ** 2

dir1 = set(dir())
dird = dir1 - dir0

for v in sorted(dird):
    print("{:} \t=\t {:}".format(v, globals()[v]))

out='''
# domain
set vect A (0, 0, 0)
set vect B ({H},{H},{W})

# initial drop
set vect IC ({x0}, {y0}, {z0})
set double IR {a}
set vect IC2 ({x02}, {y02}, {z0})
set double IR2 {a2}

# initial velocity
set vect initial_velocity ({Uc}, 0, 0)
set bool initial_pois 1

# time
set double T {T}
set double dt {dt}

# physical parameters
set int num_phases 2
#set vect force ({pgrad}, 0, 0)
set vect gravity ({pgrad}, 0, 0)
set double density_0 {rhoo}
set double density_1 {rhoi}
set double viscosity_0 {muo}
set double viscosity_1 {mui}
set double sigma -{sigma}

'''.format(**globals())

with open("par.hydroconf", 'w') as f:
    f.write(out)
