#!/usr/bin/env python

import mfer.post as mp
import numpy as np
import os 

pr = "ref/"
r1x,r1y = np.loadtxt(pr + 'xz').T
r2x,r2vx = np.loadtxt(pr + 'xu').T
lbr = "Mortazavi"

ps = "."
s = np.genfromtxt(os.path.join(ps, "exp.scalar.dat"), names=True)  
lbs = "hydro"
sx = s["cx_1"]
sy = s["cy_1"]
svx = s["vx_1"]

# plot lines
sx -= sx[0]
#ts = hs['t']
mp.plot_lines([
        {'x':sx, 'y':sy, 'lb':lbs},
        {'x':r1x, 'y':r1y, 'lb':lbr},
        ] , preset='y')

mp.plot_lines([
        {'x':sx, 'y':svx, 'lb':lbs},
        {'x':r2x, 'y':r2vx, 'lb':lbr},
        ] , preset='u')

vol = s["volume_1"]
mp.plot_lines([
        {'x':sx, 'y':(vol - vol[0]) / vol[0], 'lb':lbs},
        ] , preset='m')
