#!/usr/bin/env python

import mfer.post as mp
import numpy as np

ps = "mortazavi_Nx64"
ds = mp.get_series(ps, cache=0)
hs = mp.get_history(ds)
lbs = "hydro,Nx64"

ps2 = "mortazavi_Nx128"
ds2 = mp.get_series(ps2, cache=0)
hs2 = mp.get_history(ds2)
lbs2 = "hydro,Ny128"

pr = "ref/"
hr1x,hr1y = np.loadtxt(pr + 'xy').T
hr2x,hr2u = np.loadtxt(pr + 'xu').T
lbr = "Mortazavi"



# plot lines
xs0 = hs['x'] - hs['x'][0]
xs20 = hs2['x'] - hs2['x'][0]
#ts = hs['t']
mp.plot_lines([
        {'x':xs0, 'y':hs['y'], 'lb':lbs},
        {'x':xs20, 'y':hs2['y'], 'lb':lbs2},
        {'x':hr1x, 'y':hr1y, 'lb':lbr},
        ] , preset='y')

mp.plot_lines([
        {'x':xs0, 'y':hs['u'], 'lb':lbs},
        {'x':xs20, 'y':hs2['u'], 'lb':lbs2},
        {'x':hr2x, 'y':hr2u, 'lb':lbr},
        ] , preset='u')

vol0 = hs['vol'][0]
vol20 = hs2['vol'][0]
mp.plot_lines([
        {'x':xs0, 'y':(hs['vol']-vol0)/vol0, 'lb':lbs},
        {'x':xs20, 'y':(hs2['vol']-vol20)/vol20, 'lb':lbs2},
        ] , preset='m')
